name: Deploy challenge Dijkstra

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Java e Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build do projeto e testes
        run: mvn clean verify

      - name: verificando testes de Benchmark
        run: java -jar target/benchmarks.jar

      - name: Upload cobertura JaCoCo para o Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: create tag release
        uses: mathieudutour/github-tag-action@v6.2
        with: 
         github_token: ${{ secrets.GITHUB_TOKEN }}
         tag_prefix: "v"
         release_branches: main
